Story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
import Story_1.urls as Story_1
import Story_4.urls as Story_4
import Story_5.urls as Story_5

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Story-1/', include(Story_1, namespace='Story_1')),
    path('Story-4/', include(Story_4, namespace='Story_4')),
    path('Story-5/', include(Story_5, namespace='Story_5')),
    path('', RedirectView.as_view(url='/Story-4/', permanent=True), name='index')
]

Story_1/urls.py
from django.urls import path
from .views import index

#url for app
app_name = 'Story_1'
urlpatterns = [
    path('', index, name='index'),
]

Story_4/urls.py
from django.urls import path
from .views import index, about, resume, diary, contact, form, add_guest

#url for app, add your URL Configuration

app_name = 'Story_4'
urlpatterns = [
    path('', index, name='index'),
    path('About', about, name='about'),
    path('Resume', resume, name='resume'),
    path('Contact', contact, name='contact'),
    path('Form', form, name='form'),
    path('add_guest', add_guest, name='add_guest'),
]

Story_5/urls.py
from django.urls import path
from .views import CreateDiary, MyDiary, DiaryFormViews, DeleteDiary

#url for app, add your URL Configuration

app_name = 'Story_5'
urlpatterns = [
    path('', MyDiary, name='diary'),
    path('diary-form', DiaryFormViews, name='diary-form'),
    path('create-diary', CreateDiary, name='add_activity'),
    path('my-diary', MyDiary, name='diary'),
    path('delete-diary', DeleteDiary, name='delete_diary'),
]

Story_1/models.py
from django.db import models

# Create your models here.

Story_4/models.py
from django.db import models

# Create your models here.
class Guest(models.Model):
    name = models.CharField(max_length=27)
    email = models.EmailField()
    subject = models.CharField(max_length=27)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

Story_5/models.py
from django.db import models


class Diary(models.Model):
    name = models.CharField(max_length=27)
    date = models.DateTimeField()
    location = models.CharField(max_length=27)
    category = models.CharField(max_length=27)

    class Meta:
        verbose_name_plural = 'Diary'

    def __str__(self):
        return self.name

Story_5/forms.py
from django import forms

class DiaryForm(forms.Form):
    name = forms.CharField(label='Name', max_length=27, required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    location = forms.CharField(label='Location', max_length=27, required=True,
                                   widget=forms.TextInput(attrs={'class': 'form-control'}))
    category = forms.CharField(label='Category', max_length=27, required=True,
                                   widget=forms.TextInput(attrs={'class': 'form-control'}))
    date = forms.DateTimeField(required=True, widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),
                               input_formats=['%Y-%m-%dT%H:%M'])

Story_1/views.py
from django.shortcuts import render
from datetime import datetime, date

# Create your views here.
def index(request):
    response ={
        'my_bio':my_bio,
        'friend_bio':friend_bio,
        'my_name':my_name,
        'friend_name':friend_name,
    }
    return render(request, 'index_lab1.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

my_name = 'Muhamad Lutfi Arif'
friend_name = 'Muhammad Andriansyah Putra'
curr_year = int(datetime.now().strftime("%Y"))
my_birth_date = date(1999, 10, 23)
friend_birth_date = date(1999, 8, 22)
my_npm = '1706979360'
friend_npm = '1706044093'

my_bio = [
    {'key':'Age', 'value':calculate_age(my_birth_date.year)},
    {'key':'NPM', 'value':my_npm},
    {'key':'College', 'value':'University of Indonesia'},
    {'key':'Hobbies', 'value':'Read books, Watch movies, Gaming, Coding'},
    {'key':'Description', 'value':"I am learning to be an expert web developer right now."},
]
friend_bio = [
    {'key':'Age', 'value':calculate_age(friend_birth_date.year)},
    {'key':'NPM', 'value':friend_npm},
    {'key':'College', 'value':'University of Indonesia'},
    {'key':'Hobbies', 'value':'Watch Football, Music, Play Football'},
    {'key':'Description', 'value':"Quran FUKI staff"},
]

Story_4/views.py
from django.shortcuts import render, redirect
from .models import Guest

# Create your views here.
def index (request):
    response = {}
    return render(request, 'home.html', response)

def about (request):
    return render(request, 'about.html')

def resume (request):
    return render(request, 'resume.html')

def contact (request):
    return render(request, 'contact.html')

def diary (request):
    return redirect('Story_5:diary')

def form (request):
    return render(request, 'form.html')

def add_guest (request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']
        guest = Guest(name=name, email=email, subject=subject, message=message)
        guest.save()
    return redirect('Story_4:form')

Story_5/views.py
from django.shortcuts import render, redirect
from .forms import DiaryForm
from .models import Diary


def CreateDiary(request):
    response = {}
    schedule = DiaryForm(request.POST or None)
    if (request.method == 'POST' and schedule.is_valid()):
        response['name'] = request.POST['name']
        response['date'] = request.POST['date']
        response['location'] = request.POST['location']
        response['category'] = request.POST['category']
        schedule_form = Diary(name=response['name'],
                              date=response['date'],
                              location=response['location'],
                              category=response['category'])
        schedule_form.save()
        return redirect('Story_5:diary')
    else:
        return redirect('Story_5:diary-form')

def DiaryFormViews(request):
    response = {'form': DiaryForm}
    return render(request, "diaryForm.html", response)

def MyDiary(request):
    response = {}
    data = Diary.objects.all()
    response['data'] = data
    return render(request, 'diary.html', response)

def DeleteDiary(request):
    response = {}
    reset = Diary.objects.all().delete()
    response['reset'] = reset
    return redirect('Story_5:diary')

Story_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ my_name }}</title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
</head>
<body>
<style>
    body {
        font-family: 'Dosis', sans-serif;
        text-align: center;
        background: no-repeat center right fixed url('https://ak6.picdn.net/shutterstock/videos/20559346/thumb/5.jpg');
	    background-size: cover;
        font-size: 20px;
        line-height: 1.8;
        overflow: hidden;
    }
    img {
        margin-top: 100px;
        border: 10px solid lightgrey;
    }

    div {
        margin-top: -23px;
    }
    p {
        font-size: 15px;
        line-height: 1.8;
    }
</style>
    <header>
        <h1 style="font-size: 70px">Hello, World!</h1>
        <h4 style="margin-top: -10px">Welcome to My First Website</h4>
    </header>
    <div class="col-md-12">
        <div class="container">
            <div class="row2">
                <div class="col-md-4">
                    <img class="img-circle" src="https://pbs.twimg.com/media/DmYgHO6W0AAriuu.jpg" width="160" height="160">
                    <h3><strong>Wall</strong></h3>
                    <p>
                        Just a White Wall beside me.
                    </p>
                </div>
                <div class="col-md-4">
                    <img class="img-circle" src="https://pbs.twimg.com/media/DmdGUTyU0AAp3dU.jpg" width="160" height="160">
                    <h3><strong>{{ my_name }}</strong></h3>
                    <p>
                        {% for bio in my_bio %}
                            <strong> {{ bio.key }} </strong>
                            <br >{{ bio.value }}<br>
                        {% endfor %}
                    </p>
                </div>
                <div class="col-md-4">
                    <img class="img-circle" src="https://pbs.twimg.com/media/DmdICWVV4AEE6WJ.jpg" width="160" height="160">
                    <h3><strong>{{ friend_name }}</strong></h3>
                    <p>
                        {% for bio in friend_bio %}
                            <strong> {{ bio.key }} </strong>
                            <br >{{ bio.value }}<br>
                        {% endfor %}
                    </p>
                </div>
            </div>
        </div>
    </div>
    <p style="color:darkblue; font-size: 14px; margin-top: 538px">&copy; Made with Love by {{ my_name }} </p>
</body>
</html>

Story_4/templates/about.html
{% extends "layout/base.html" %}

{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static "css/about.css" %}">
{% endblock style %}

{% block content %}
    <div id="about" class="col-md-12">
        <div class="container">
            <h1 style="font-weight: bolder">My Profile</h1>
            <p class="lead">"The best of you are those who benefits others"</p>
            <hr>
            <div class="row">
                <div style="box-shadow: 10px 10px 0px rgba(0,0,0,0.1);" class="about1 col-md-4">
                    <h3>Who Am I ?</h3>
                    <h5 style="font-family: 'Titillium Web', sans-serif; font-weight: lighter; font-style: italic">An Amateur Programmer Located in Our Lovely Earth</h5>
                    <p>I am a college student of Computer Science University of Indonesia. I am Introvert person. I love to be helpful for others. I always be cheerful and be friendly with others. I am learning to be an expert web developer right now and I have a dream to work at Google soon.
                    </p>
                </div>
                <div style="box-shadow: 10px 10px 0px rgba(0,0,0,0.1);" class="foto-about col-md-4">
                    <img src="{% static "img/profile.jpg" %}" alt="Programmer Sholeh">
                </div>
                <div style="box-shadow: 10px 10px 0px rgba(0,0,0,0.1);" class="about2 col-md-4">
                    <h3>Details</h3>
                    <p>
                        <strong>Name</strong>
						<br>Muhamad Lutfi Arif<br>
                        <strong>Birthdate</strong>
						<br>October 23, 1999<br>
						<strong>Age</strong>
						<br>18 years old<br>
                        <strong>Phone</strong>
						<br>+62 813-1754-1282<br>
                        <strong>Email</strong>
						<br>Larif216@gmail.com<br>
						<strong>Location</strong>
						<br>Central Jakarta, DKI Jakarta, Indonesia<br>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

Story_4/templates/contact.html
{% extends "layout/base.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static "css/contact.css" %}">
{% endblock style %}
{% block content %}
<body id="cont">
        <div id="particles-js"></div>
        <div id="contact">
            <ul>
                <li><a href="https://www.facebook.com/luthfi216"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href="http://twitter.com/luthfi216"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                <li><a href="https://plus.google.com/114146989066324651951"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                <li><a href="https://www.linkedin.com/in/muhamad-lutfi-arif-817765168/"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                <li><a href="https://www.instagram.com/luthfi216/"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
            </ul>
        </div>
</body>

{% endblock content %}

Story_4/templates/form.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>Muhamad Lutfi Arif</title>
    <script src='//production-assets.codepen.io/assets/editor/live/console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js'></script><script src='//production-assets.codepen.io/assets/editor/live/events_runner-73716630c22bbc8cff4bd0f07b135f00a0bdc5d14629260c3ec49e5606f98fdd.js'></script><script src='//production-assets.codepen.io/assets/editor/live/css_live_reload_init-2c0dc5167d60a5af3ee189d570b1835129687ea2a61bee3513dee3a50c115a77.js'></script><meta charset='UTF-8'><meta name="robots" content="noindex"><link rel="shortcut icon" type="image/x-icon" href="//production-assets.codepen.io/assets/favicon/favicon-8ea04875e70c4b0bb41da869e81236e54394d63638a1ef12fa558a4a835f1164.ico" /><link rel="mask-icon" type="" href="//production-assets.codepen.io/assets/favicon/logo-pin-f2d2b6d2c61838f7e76325261b7195c27224080bc099486ddd6dccb469b8e8e6.svg" color="#111" /><link rel="canonical" href="https://codepen.io/shamelin/pen/NqoLzO?depth=everything&order=popularity&page=14&q=services&show_forks=false" />
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,100,500' rel='stylesheet' type='text/css'>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>

<style>
body {
    height: 100%;
    width: 100%;
    overflow: hidden;
    margin-top: -2px;
    position: relative;
}
.main-connection-div {
    margin-top: 5%;
    margin-left: 60%;
    padding: 20px;
    background: rgba(250, 250, 250, 0.9);
    width:400px;
    height:570px;
    position: absolute;
    box-shadow: 0 5px 15px rgba(0, 0, 0, 1);
    border-radius: 5px;
}

.log-in-main-connection-div {
    width: 100%;
    left: 0;
    float: left;
}


.title-log-in-main-connection-div {
    color: #0072ff;
    font-family: 'Roboto', sans-serif;
    font-size: 24px;
    font-weight: 300;
    margin: 5px 0 0 15px;
    padding: 0;
}


.main-connection-div .input-field {
    width: 80%;
    margin: 20px 0 0 30px;
}

/* label focus color */
.main-connection-div .input-field input[type=text]:focus + label {
    color: #0072ff;
    left: 0.1rem;
}

.input-field label.active {
    left: 0.1rem;
}

/* label underline focus color */
.main-connection-div .input-field input[type=text]:focus {
    border-bottom: 1px solid #0072ff;
    box-shadow: 0 1px 0 0 #0072ff;
}

/* valid color */
.main-connection-div .input-field input[type=text].valid {
    border-bottom: 1px solid #2ecc71;
    box-shadow: 0 1px 0 0 #2ecc71;
}

/* invalid color */
.main-connection-div .input-field input[type=text].invalid {
    border-bottom: 1px solid #e74c3c;
    box-shadow: 0 1px 0 0 #e74c3c;
}
/* label focus color */
.main-connection-div .input-field input[type=email]:focus + label {
    color: #0072ff;
    left: 0.1rem;
}

.input-field label.active {
    left: 0.1rem;
}

/* label underline focus color */
.main-connection-div .input-field input[type=email]:focus {
    border-bottom: 1px solid #0072ff;
    box-shadow: 0 1px 0 0 #0072ff;
}

/* valid color */
.main-connection-div .input-field input[type=email].valid {
    border-bottom: 1px solid #2ecc71;
    box-shadow: 0 1px 0 0 #2ecc71;
}

/* invalid color */
.main-connection-div .input-field input[type=email].invalid {
    border-bottom: 1px solid #e74c3c;
    box-shadow: 0 1px 0 0 #e74c3c;
}

.options-alert a, button {
    text-transform: uppercase;
    font-family: 'Roboto', sans-serif;
    color: #777;
    padding: 8px 20px;
    margin-right: 10px;
    border-radius: 2px;
}

.options-alert a:hover {
    background: rgba(0, 0, 0, 0.1);
}

.options-alert a:active {
    background: rgba(0, 0, 0, 0.2);
}

a, button {
    color: #0072ff;
}
iframe {
    z-index: -100;
    position: absolute;
    width: 100vw;
    height: 100vh;
    overflow-y: scroll;
    padding-right: 17px; /* Increase/decrease this value for cross-browser compatibility */
    box-sizing: content-box; /* So the width will be 100% + 17px */
}
@media only screen and (max-width: 400px) {
    .main-connection-div {
        margin: 0%;
        padding: 20px;
        background: rgba(250, 250, 250, 0.8);
        width:400px;
        height:570px;
        position: absolute;
        box-shadow: 0 5px 15px rgba(0, 0, 0, 1);
    }
}
</style>
</head>
<body>
    <div id="map"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3966.5964915176205!2d106.84510931471644!3d-6.184721495522507!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69f44f49facefb%3A0x240fe7f4b1156e63!2sJl.+Kramat+Pulo+Dalam+2%2C+Kramat%2C+Senen%2C+Kota+Jakarta+Pusat%2C+Daerah+Khusus+Ibukota+Jakarta+10450!5e0!3m2!1sid!2sid!4v1537954529820" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
    <div class="main-connection-div" id="main-connection-div">
        <div class="log-in-main-connection-div" id="log-in-main-connection-div">
            <p class="title-log-in-main-connection-div">Guest Form</p>
            <form id="form" method="POST" action="{% url 'Story_4:add_guest' %}">
                {% csrf_token %}
                <div class="input-field col s6">
                    <input type="text" name="name" id="username intert-textarea"class="validate" required>
                    <label for="username">Username</label>
                </div>
                <div class="input-field col s6">
                    <input type="email" name="email" id="username intert-textarea" class="validate" required>
                    <label for="email">Email</label>
                </div>
                <div class="input-field col s6">
                    <input type="text" name="subject" id="username intert-textarea" class="validate" required>
                    <label for="subject">Subject</label>
                </div>
                <div class="input-field col s6">
                    <textarea style="height: 110px; resize: none" name="message" required type="text" id="username intert-textarea" class="validate"></textarea>
                </div>
                <div class="row">
                    <a href="{% url "Story_4:index" %}" class="waves-effect waves-light btn-large" style="margin: 20px 0 0 30px; background: #0072ff;">Back</a>
                    <button name="myButton" type="submit" class="waves-effect waves-light btn-large" style="margin: 20px 0 0 68px; background: #0072ff;" onclick="this.disabled=true;this.form.submit();">Submit</button>
                </div>
            </form>
        </div>
    </div>
    <script type="text/javascript">
        function checkForm(form)
        {
            //
            // validate form fields

            form.myButton.disabled = true;
            return true;
        }

</script>
</body>
</html>

Story_4/templates/home.html
{% extends "layout/base.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static "css/home.css" %}">
{% endblock style %}
{% block content %}
<body id="home">
    <div id="particles-js"></div>
    <div class="container" id="greet">
        <h1 class="display-4">Hello, World!</h1>
        <p class="lead">Welcome to My First Site</p>
        <a href="{% url 'Story_4:form' %}">Guest Form</a>
    </div>
</body>

{% endblock content %}

Story_4/templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Muhamad Lutfi Arif</title>
    {% include "partials/source.html" %}
    {% block style %}
        <!-- import css here -->
    {% endblock style %}
</head>
<body>
    <header>
        {% include "partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </div>
    </content>
    <footer>
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>
    <script src="{% static "js/particles.js" %}"></script>
    <script src="{% static "js/app.js" %}"></script>
</body>
</html>

Story_4/templates/partials/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="z-index: 1000">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Story_4:index' %}">HOME <i class="fa fa-home"></i><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Story_4:about' %}">ABOUT <i class="fa fa-user"></i><span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'Story_4:resume' %}">RESUME <i class="fa fa-file-text"></i><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Story_4:index' %}">
            <h2>Muhamad Lutfi Arif</h2>
            <h5>Your Future Programmer</h5>
            <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Story_5:diary' %}">DIARY <i class="fa fa-book"></i><span class="sr-only">(current)</span></a>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Story_4:contact' %}">CONTACT <i class="fa fa-comments-o"></i><span class="sr-only">(current)</span></a>
      </li>
      </li>
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'Story_4:form' %}">GUEST FORM <i class="fa fa-address-book"></i><span class="sr-only">(current)</span></a>
      </li>

    </ul>
  </div>
</nav>

Story_4/templates/partials/source.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Titillium+Web:200,300,300i,400,600|Russo+One|Marcellus+SC" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

Story_5/templates/diary.html
{% extends 'layout/base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static "css/diary.css" %}">
{% endblock style %}
{% block content %}
    <div class="main-div">
        <div class="container">
            <h1 style="text-align: center" class="text-main">My Diary</h1>
            <hr>
            <a href="{% url 'Story_5:diary-form' %}">Add Activity<i class="fa fa-pencil-square-o"></i></a>
            <a href="{% url 'Story_5:delete_diary' %}">Reset Diary<i class="fa fa-trash"></i></a>
            <div id="list" class="container mx-auto d-block">
            {% if data %}
                <table class="table table-hover table-bordered table-striped table-red" align="center" style="text-align: center">
                    <thead>
                        <tr>
                            <th scope="col">Activities</th>
                            <th scope="col">Place</th>
                            <th scope="col">Category</th>
                            <th scope="col">Date, Time</th>
                        </tr>
                    </thead>
                    {% for item in data %}
                        <tr>
                            <td scope="row">{{ item.name }}</td>
                            <td scope="row">{{ item.location }}</td>
                            <td scope="row">
                                {% if item.category %}
                                    {{ item.category }}
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td scope="row">
                                {{ item.date|date:"l" }}, {{ item.date }}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <h1 class="text-main">There is no activity</h1>
            {% endif %}
        </div>
        </div>
    </div>
{% endblock content %}

Story_5/templates/diaryForm.html
{% extends 'layout/base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static "css/diaryForm.css" %}">
{% endblock style %}
{% block content %}
        <div id="form" class="container">
            <h1>Add Activity</h1>
            <hr>
                <form action={% url 'Story_5:add_activity' %} method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" value="Submit">Submit</button>
            </form>
        </div>
{% endblock %}